Levelup/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('',include('django.contrib.auth.urls')),
]

app/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
from .forms import MyPasswordChangeForm,MyPasswordResetForm,MySetPasswordForm
# from django.urls import path
# from app.views import popup
app_name ='app'
urlpatterns = [
   path('',views.home,name='home'),
   path('register/',views.register_attempt,name='register'),
   path('accounts/login/',views.login_attempt,name='login'),
   path('logout/',views.user_logout,name='logout'),
   path('token/',views.token_send,name='token_send'),
   path('success/',views.success,name='success'),
   path('verify/<auth_token>/',views.verify,name='verify'),
   path('error/',views.error_page,name='error'),
   path('details/',views.DetailView.as_view(),name='details'),
   # path('run/',views.runcode,name='run'),
   path('password-reset/',auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',form_class=MyPasswordResetForm),name='password_reset'),
   path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'),name='password_reset_done'),
   path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_confirm'),
   path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'),name='password_reset_complete'),
   path('passwordchange/',auth_views.PasswordChangeView.as_view(template_name='app/passwordchange.html',form_class=MyPasswordChangeForm),name='password_change'),
   path('passwordchangedone/',auth_views.PasswordChangeView.as_view(template_name='app/passwordchangedone.html'),name='passwordchangedone'),
   path('enquiry/',views.Enquiry,name='enquiry'),
   path('success_page/',views.Success_page,name='success_page') ,
   # path('popup/',views.popup, name='popup')

 
   
]

app/templates/app/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>

<!-- Popper JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<form method="post" class="form-control">
        {% csrf_token %}
    <div class="from-group">
        <input type="text" placeholder="user name" required name="usr"><br>
        <input type="text" placeholder="first name" required name="first_name"><br>
        <input type="text" placeholder="last name" required name="last_name"><br>
        <input type="email" name="email" placeholder="email" required><br>
        <input type="number" name="phone" placeholder="number" required><br>
        <input type="submit" name="submit">
    </div>
</form>
</body>
</html>

app/templates/app/enquiry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>

<!-- Popper JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <form method="POST" class="form-control">
        {% csrf_token %}
    <div class="form-group">
        <input type="text" placeholder="Name" required name="username"><br>
        <!-- <input type="phone number" name="phone number" placeholder="number" required><br> -->
        <input type="email" name="email" placeholder="email" required><br>
        <!-- <input type="password" name="password" placeholder="password" required> <br> -->
        <!-- <textarea name="text" id="" cols="30" placeholder="messages" rows="2"></textarea><br> -->
        <input type="submit" name="submit">
    </div>
    </form>
</body>
</html>

app/templates/app/enquiry_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<h1>your details are successfully  submited</h1>
<!-- <a href="https://youtu.be/PkR3kpxeJZ8"></a> -->
<a href="https://www.youtube.com/watch?v=PkR3kpxeJZ8">click me</a>
<!-- <img src="{% static 'app/home(1).png'%}" alt="no img"> -->
<img src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FIMG_%2528company%2529&psig=AOvVaw01h8dwcGO9ohB8vv5AJ5WF&ust=1676697877835000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCJDJgb3om_0CFQAAAAAdAAAAABAE" alt="">
</body>
</html>

app/templates/app/login.html
{% extends "app/home.html"%}
{% block content %}

    <div class="global-container">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Log in to Django</h3>
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}

        {% endif %}
            <div class="card-text">
                <!--
                <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->
                <form method="post">
                    {% csrf_token %}
                    <!-- to error: add class "has-danger" -->
                    <div class="form-group">
                        <label for="exampleInputEmail1">Username</label>
                        <input type="text" name="username" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>

                        <input type="password" name="password" class="form-control form-control-sm" id="exampleInputPassword1">
                    </div>
                    <div>
                        <a href="{% url 'app:password_reset' %}" style="float:right;font-size:12px;">Forgot password?</a>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Sign in</button>


                </form>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

app/templates/app/password_reset.html
{% extends 'app/home.html' %}
{% load static %}
{% block title %}Reset Password{% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset my-3">
      <h3>Reset Password</h3>
      <hr>
      <form action="" method="post" novalidate class="shadow p-5">
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group mb-3">
          {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small>
        </div>
        {% endfor %}
        <input type="submit" value="submit" class="btn btn-primary">
        {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
                {% endif %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

app/templates/app/password_reset_complete.html
{% extends 'app/home.html' %}
{% load static %}
{% block title %}Password Reset Confirm {% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h4>Reset Password Completed !</h4>
            <div><iframe src="https://giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200" frameborder="0" class="giphy-embed" allowFullScreen></iframe></div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/password_reset_confirm.html
{% extends 'app/home.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="col-sm-6 offset-sm-3">
    <h3>Password Reset Confirm</h3>
    <hr>
    <form action=" " method="post" novalidate class="shadow p-5">
      {% csrf_token %}
      {% for fm in form %}
      <div class="form-group">
        {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small><br>

      </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary mt-3" value="Submit">
      {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
      <p class="alert alert-danger my-3">{{error}}</p>
      {% endfor %}
      {% endif %}
    </form>
  </div>
</div>

{% endblock %}

app/templates/app/password_reset_done.html
{% extends 'app/home.html' %}
{% load static %}
{% block title %}Password Reset Done{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h4 class="alert-heading">Well Done !</h4>
            <p>An Email has been sent with instructions to reset your password.<b>Check your Email</b></p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/passwordchange.html
{% extends 'app/home.html' %}
{% load static %}
{% block content %}
{% block title %}Change Password{% endblock title %}
<div class="container">
    <div class="row">
        <h3>Welcome User</h3>
        <div class="col-sm-2 border end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'app:password_change' %}" class="btn btn-success">Change Password</a></li>
            </ul>
        </div>
        <div class="col-sm-6 offset-sm-3">
            <h3>Login</h3>
            <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group mb-3">
                    {{fm.label_tag}}{{fm}}<small class="text-danger">{{fm.errors|striptags}}</small>
                </div>
                {% endfor %}
                <input type="submit" value="Submit" class="btn btn-primary">
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
                {% endif %}
            </form>
    </div>
</div>
{% endblock %}

app/templates/app/passwordchangedone.html
{% extends 'app/home.html' %}
{% load static %}
{% block title %}Change Password Done{% endblock title %}
{% block content %}
<div class="container my-5">
  <div class="row">
    <h3>Welcome John</h3>
    <div class="col-sm-3 border-end">
      <ul class="list-unstyled">
        <li class="d-grid"><a href="{% url 'app/details' %}" class="bnt btn-primary">Change Password Done</a></li>
      </ul>
    </div>
    <div class="col-sm-9 offset-sm-1 text-center">
      <h3>Password Changed Successfully !</h3>
      <div><iframe src="https://giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200" frameborder="0" class="giphy-embed" allowFullScreen></iframe></div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/app/popup.html
<!-- {% extends 'app/home.html' %}

{% block content %}
<div class="popup">
    <h2>Subscribe to our newsletter</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %} -->

app/templates/app/register.html
{% extends "app/home.html" %}
{% block content %}


    <div class="global-container">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Register in to Django</h3>
            <div class="card-text">
                {% if messages %}

                        {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                        {% endfor %}

                    {% endif %}
                <!--

                <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->
                <form method="post">
                    {%  csrf_token %}


                    <!-- to error: add class "has-danger" -->
                    <div class="form-group">
                        <label for="exampleInputEmail1">Username</label>
                        <input type="text" name="username" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" name="email" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputphone">Phone</label>
                        <input type="text" name="phone" class="form-control form-control-sm" id="exampleInputphone" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" name="password" class="form-control form-control-sm" id="exampleInputPassword1">
                    </div>
                 <div class="form-group">
                        <label for="exampleInputPassword2">Confirm Password</label>
                        <input type="password" name="confirm password" class="form-control form-control-sm" id="exampleInputPassword2">
                    </div>
                    <!-- <a href="#" style="float:right;font-size:12px;">Forgot password?</a> -->

                    <button type="submit" class="btn btn-primary btn-block mt-2">Sign in</button>


                </form>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

app/templates/app/success_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
 
<h1>successfully submit</h1>

</body>
</html>